/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Sample User API
 * OpenAPI spec version: 1.0.0
 */
import { axiosInstance } from './axios-instance';
export interface FiltersFilterOption {
  value: string;
  label: string;
}

export interface UsersUser {
  id: string;
  name: string;
  email: string;
}

export type UsersListUsersParams = {
q?: string;
};

export const getSampleUserAPI = () => {
const filtersListDepartmentOptions = (
    
 ) => {
      return axiosInstance<FiltersFilterOption[]>(
      {url: `/api/filters/departments`, method: 'GET'
    },
      );
    }
  
const filtersListSkillOptions = (
    
 ) => {
      return axiosInstance<FiltersFilterOption[]>(
      {url: `/api/filters/skills`, method: 'GET'
    },
      );
    }
  
const usersListUsers = (
    params?: UsersListUsersParams,
 ) => {
      return axiosInstance<UsersUser[]>(
      {url: `/api/users`, method: 'GET',
        params
    },
      );
    }
  
return {filtersListDepartmentOptions,filtersListSkillOptions,usersListUsers}};
export type FiltersListDepartmentOptionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSampleUserAPI>['filtersListDepartmentOptions']>>>
export type FiltersListSkillOptionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSampleUserAPI>['filtersListSkillOptions']>>>
export type UsersListUsersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSampleUserAPI>['usersListUsers']>>>
