/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Sample Item API
 * OpenAPI spec version: 1.0.0
 */
import { axiosInstance } from './axios-instance';
export interface FiltersFilterOption {
  value: string;
  label: string;
}

export interface FiltersFilterOptionsResponse {
  items: FiltersFilterOption[];
}

export interface ItemsSampleItem {
  id: string;
  name: string;
  email: string;
  segment: string;
  employment: string;
  joinedAt: string;
  tokens: string[];
  features: string[];
}

export interface ItemsSampleItemsResponse {
  items: ItemsSampleItem[];
}

export type ItemsListSampleItemsParams = {
q?: string;
tokens?: string[];
sections?: string[];
joinedAfter?: string;
sort?: ItemsListSampleItemsSort;
features?: string[];
};

export type ItemsListSampleItemsSort = typeof ItemsListSampleItemsSort[keyof typeof ItemsListSampleItemsSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ItemsListSampleItemsSort = {
  'joined-asc': 'joined-asc',
  'joined-desc': 'joined-desc',
} as const;

export const getSampleItemAPI = () => {
const filtersListSectionOptions = (
    
 ) => {
      return axiosInstance<FiltersFilterOptionsResponse>(
      {url: `/api/filters/sections`, method: 'GET'
    },
      );
    }
  
const filtersListTokenOptions = (
    
 ) => {
      return axiosInstance<FiltersFilterOptionsResponse>(
      {url: `/api/filters/tokens`, method: 'GET'
    },
      );
    }
  
const itemsListSampleItems = (
    params?: ItemsListSampleItemsParams,
 ) => {
      return axiosInstance<ItemsSampleItemsResponse>(
      {url: `/api/fizz`, method: 'GET',
        params
    },
      );
    }
  
return {filtersListSectionOptions,filtersListTokenOptions,itemsListSampleItems}};
export type FiltersListSectionOptionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSampleItemAPI>['filtersListSectionOptions']>>>
export type FiltersListTokenOptionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSampleItemAPI>['filtersListTokenOptions']>>>
export type ItemsListSampleItemsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSampleItemAPI>['itemsListSampleItems']>>>
