/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Sample User API
 * OpenAPI spec version: 1.0.0
 */
import { axiosInstance } from './axios-instance';
export interface FiltersFilterOption {
  value: string;
  label: string;
}

export interface FiltersFilterOptionsResponse {
  items: FiltersFilterOption[];
}

export interface UsersUser {
  id: string;
  name: string;
  email: string;
  department: string;
  employment: string;
  joinedAt: string;
  skills: string[];
  features: string[];
}

export interface UsersUsersResponse {
  users: UsersUser[];
}

export type UsersListUsersParams = {
q?: string;
skills?: string[];
departments?: string[];
joinedAfter?: string;
sort?: UsersListUsersSort;
features?: string[];
};

export type UsersListUsersSort = typeof UsersListUsersSort[keyof typeof UsersListUsersSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsersListUsersSort = {
  'joined-asc': 'joined-asc',
  'joined-desc': 'joined-desc',
} as const;

export const getSampleUserAPI = () => {
const filtersListDepartmentOptions = (
    
 ) => {
      return axiosInstance<FiltersFilterOptionsResponse>(
      {url: `/api/filters/departments`, method: 'GET'
    },
      );
    }
  
const filtersListSkillOptions = (
    
 ) => {
      return axiosInstance<FiltersFilterOptionsResponse>(
      {url: `/api/filters/skills`, method: 'GET'
    },
      );
    }
  
const usersListUsers = (
    params?: UsersListUsersParams,
 ) => {
      return axiosInstance<UsersUsersResponse>(
      {url: `/api/users`, method: 'GET',
        params
    },
      );
    }
  
return {filtersListDepartmentOptions,filtersListSkillOptions,usersListUsers}};
export type FiltersListDepartmentOptionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSampleUserAPI>['filtersListDepartmentOptions']>>>
export type FiltersListSkillOptionsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSampleUserAPI>['filtersListSkillOptions']>>>
export type UsersListUsersResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSampleUserAPI>['usersListUsers']>>>
